# Task 1

In [1]:
import numpy as np
import scipy.linalg as sla

In [35]:
def solve(matrix, vector, pos):
    alpha = matrix[pos].dot(vector)
    if np.abs(alpha) < 1e-9:
        return
    size = matrix.shape[0]
    d = np.eye(size)
    z = matrix.dot(vector)
    kth = z[pos]
    z[pos] = -1
    z = -z / kth
    d[:, pos] = z
    return d @ matrix


def check(matrix, solution):
    print(matrix @ solution)
    return sla.norm(sla.inv(matrix) - solution, 'fro')


In [3]:
matrix = np.array([[1, 2, 1], [4, 6, 6], [7, 8, 9]])
vector = np.array([1, 4, 9])
c_ = matrix.copy()
pos = 1
c_[:, pos] = vector
result = solve(sla.inv(matrix), vector, pos)

check(c_, result)


[[ 1.00000000e+00 -5.55111512e-17  0.00000000e+00]
 [ 1.77635684e-15  1.00000000e+00  1.11022302e-16]
 [ 3.55271368e-15 -4.99600361e-16  1.00000000e+00]]


1.5740127955196998e-15

# Task 2

In [37]:
def find_inverse(matrix):
    size = matrix.shape[0]
    J = set(range(size))
    B = np.eye(size)
    s = [0] * size
    for i in range(size):
        singular = True
        for j in J:
            curr = solve(B, matrix[j], i)
            if curr is not None:
                singular = False
                J.remove(j)
                B = curr
                s[j] = i
                break
        
        if singular:
            print("Singular matrix")
            return
    
    print(s)
    
    result = np.eye(size)
    for i in range(size):
        result[i] = B[s[i]]
        
    return result.transpose()

In [42]:
# matrix = np.array([[1, 2, 1, 52], [4, 6, 6, 3], [7, 8, 9, 147], [3, 3, 3, 3]])
# matrix = np.array([[0, 2, 1], [0, 1, 1], [1, 1, 1]])
# matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
eps = 2
matrix = np.array([[1, 0, 1 + eps, 1],
                 [2, -2, eps, 1],
                 [-3, 1, -2 + eps, 0],
                 [2, -4, -2 + eps, 1]])
# eps = 0 - singualr, otherwise det != 0, проверка на погрешность
# matrix = np.array([[0, 0, 4, 3], [0, 0, 0, 1], [0, 2, 0, 0], [1, 1, 0, 0]])
# non-singular
# x = 82
# matrix = np.array([[1, 8, 6, -3, 2],
#                   [4, -3, -5, 1, 0],
#                   [-8, 2, 6, -27, 81],
#                   [6, -4, 8, 5, 3],
#                  [-2, -2, 14, -22, x]])

# matrix = np.array([[1, 0, 0, -1, -1],
#                  [-1, -1, 0, 0, 0],
#                  [0, 0, 0, 1, 1],
#                  [0, 1, 1, 0, 0],
#                  [0, 0, -1, 0, 0]])
result = find_inverse(matrix)
print(result)
if result is not None:
    print(check(matrix, result))

[0, 1, 2, 3]
[[ 0.5  -0.75 -0.5   0.25]
 [ 1.5  -2.25 -0.5   0.75]
 [-1.5   2.75  0.5  -1.25]
 [ 5.   -7.5  -1.    3.5 ]]
[[ 1.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]
 [-8.88178420e-16  1.00000000e+00  0.00000000e+00 -4.44089210e-16]
 [ 2.22044605e-16 -8.88178420e-16  1.00000000e+00  4.44089210e-16]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]]
2.8705223695464124e-15
