# Лабораторная работа № 3
## Двойственный симплекс метод
## Дополнительное задание

### Выполнил: Яковлев Артур, 853501
### Проверила: Костюкова О.И.

### Вариант 7

Импорт необходиых модулей

In [18]:
import numpy as np
import scipy.linalg as sla
from copy import deepcopy
from warnings import filterwarnings


filterwarnings('ignore')

Исходные данные для пункта а)

In [12]:
dataset = {
    'A': np.array([
        [ 1., -1., 0.,  2., -1., -1., 2., 1., 7.],
        [-1.,  2., 1.,  3.,  0.,  1., 1., 1., 1.],
        [ 1., -1., 1.,  0.,  1.,  4., 4., 1., 2.],
        [ 1., -3., 0., -8.,  2.,  3., 0., 1., 1.]
    ]),
    'c': np.array([12., -24., -6., -34., -1., 4., 7., 3., 23.]),
    'b': np.array([2.5, 22., 36.5, -18.]),
    'lower': np.array([-1., -4., -1., 4., -3., 4., 0., -1., -4.]),
    'upper': np.array([3., 0., 6., 7., 4., 8., 4., 4., 1.]),
    'Jb': [0, 2, 5, 8],
}
eps = 1e-9

Исходные данные для пункта б)

In [13]:
dataset_b = {
    'A': np.array([
        [ 1., -1., 0.,  2., -1., -1., 2., 1., 7.],
        [-1.,  2., 1.,  3.,  0.,  1., 1., 1., 1.],
        [ 1., -1., 1.,  0.,  1.,  4., 4., 1., 2.],
        [ 1., -3., 0., -8.,  2.,  3., 0., 1., 1.]
    ]),
    'c': np.array([12., -24., -6., -34., -1., 4., 7., 3., 23.]),
    'b': np.array([2.5, 22., 36.5, -18.]),
    'lower': np.array([-1., -4., -1., 4., -3., 4., 0., -1., -4.]),
    'upper': np.array([3., 0., 6., 7., 4., 8., 4., 4., 1.]),
    'Jb': [0, 2, 3, 4],
}

Исходные данные для пункта в)

In [14]:
dataset_c = {
    'A': np.array([
        [ 1., -1., 0.,  2., -1., -1., 2., 1., 7.],
        [-1.,  2., 1.,  3.,  0.,  1., 1., 1., 1.],
        [ 1., -1., 1.,  0.,  1.,  4., 4., 1., 2.],
        [ 1., -3., 0., -8.,  2.,  3., 0., 1., 1.]
    ]),
    'c': np.array([12., -24., -6., -34., -1., 4., 7., 3., 23.]),
    'b': np.array([2., -20., -4., -10.]),
    'lower': np.array([-1., -4., -1., 4., -3., 4., 0., -1., -4.]),
    'upper': np.array([3., 0., 6., 7., 4., 8., 4., 4., 1.]),
    'Jb': [0, 2, 5, 8],
}

Исходные данные для пункта г)

In [15]:
dataset_d = {
    'A': np.array([
        [ 1., -1., 0.,  2., -1., -1., 2., 1., 7.],
        [-1.,  2., 1.,  3.,  0.,  1., 1., 1., 1.],
        [ 1., -1., 1.,  0.,  1.,  4., 4., 1., 2.],
        [ 1., -3., 0., -8.,  2.,  3., 0., 1., 1.]
    ]),
    'c': np.array([12., -24., -6., -34., -1., 4., 7., 3., 23.]),
    'b': np.array([2.5, 22., 36.5, -18.]),
    'lower': np.array([-1., -4., -1., 4., -3., 4., 0., -1., -4.]),
    'upper': np.array([3., 0., -1., 7., -3., 8., 4., 4., 1.]),
    'Jb': [0, 2, 5, 8],
}

Реализация двойственного симплекс метода с ограничениями

In [16]:
def solve(data, max_iters=20, verbose=True):
    dataset = deepcopy(data)
    B = sla.inv(dataset['A'][:, dataset['Jb']])
    
    if verbose:
        print(f'A_b = {dataset["A"][:, dataset["Jb"]]}')
        print(f'c_b = {dataset["c"][dataset["Jb"]]}')
        print(f'B = {B}')
        print(f'Jb = {dataset["Jb"]}')
    
    # Step 1
    y = dataset['c'][dataset['Jb']] @ B
    delta_j = y @ dataset['A'] - dataset['c']
    Jn = [i for i in range(dataset['c'].shape[0]) if i not in dataset['Jb']]
    Jn_pos = [i for i in Jn if delta_j[i] > -eps]
    Jn_neg = [i for i in Jn if delta_j[i] <= -eps]
    
    if verbose:
        print('\nStep 1\n')
        print(f'y = {y}')
        print(f'delta j = {delta_j}')
        print(f'Jn = {Jn}')
        print(f'Jn+ = {Jn_pos}')
        print(f'Jn- = {Jn_neg}')
    
    for it in range(max_iters):
        # Step 2
        x = np.zeros(dataset['c'].shape[0])
        x[Jn_pos] = dataset['lower'][Jn_pos]
        x[Jn_neg] = dataset['upper'][Jn_neg]
        x[dataset['Jb']] = B.dot(dataset['b'] - np.sum(dataset['A'][:, Jn] * x[Jn], axis=1))
        # x[dataset['Jb']] = B.dot(dataset['b'] - sum([dataset['A'][:, j].dot(x[j]) for j in Jn]))
        
        if verbose:
            print('\n===========================================\n')
            print(f'Iteration {it + 1}')
            print('\nStep 2\n')
            print(f'x = {x}')

        # Step 3
        if np.all(dataset['lower'] < x + eps) and np.all(x - eps < dataset['upper']):
            print(f'\nOptimal plan: {x}\n')
            print(f'cx = {dataset["c"] @ x}')
            return

        # Step 4
        for i in range(len(dataset['Jb'])):
            j_i = dataset['Jb'][i]
            if dataset['lower'][j_i] > x[j_i] or x[j_i] > dataset['upper'][j_i]:
                j_k = i
                break
        
        if verbose:
            print('\nStep 4\n')
            print(f'jk = {dataset["Jb"][j_k]}')

        # Step 5
        mu_jk = 1 if x[dataset["Jb"][j_k]] < dataset['lower'][dataset["Jb"][j_k]] else -1
        delta_y = mu_jk * B[j_k]
        mu_j = delta_y @ dataset['A']
        
        if verbose:
            print('\nStep 5\n')
            print(f'mu_jk = {mu_jk}')
            print(f'delta y = {delta_y}')
            print(f'mu_j = {mu_j}')

        # Step 6
        sigma_j = np.array([np.inf] * dataset['c'].shape[0])
        for i in Jn_pos:
            if mu_j[i] < eps:
                sigma_j[i] = -delta_j[i] / mu_j[i]

        for i in Jn_neg:
            if mu_j[i] > -eps:
                sigma_j[i] = -delta_j[i] / mu_j[i]
        
        j0 = np.argmin(sigma_j)
        sigma0 = sigma_j[j0]
        # To prevent -inf as sigma0
        while sigma0 == -np.inf:
            sigma_j[j0] = np.inf
            j0 = np.argmin(sigma_j)
            sigma0 = sigma_j[j0]
        
        if verbose:
            print('\nStep 6\n')
            print(f'sigma_j = {sigma_j}')
            print(f'j* = {j0}')
            print(f'sigma0 = {sigma0}')

        # Step 7
        if sigma0 == np.inf:
            print('\nSolution does not exist')
            return

        # Step 8
        delta_j += sigma0 * mu_j
        dataset['Jb'].pop(j_k)
        delta_j[dataset['Jb']] = 0.
        dataset['Jb'] = [j0] + dataset['Jb']
        # dataset['Jb'].sort()
        
        if verbose:
            print('\nStep 8\n')
            print(f'New delta j = {delta_j}')
            print(f'Jb = {dataset["Jb"]}')
        
        # Step 9
        B = sla.inv(dataset['A'][:, dataset['Jb']])
        Jn = [i for i in range(dataset['c'].shape[0]) if i not in dataset['Jb']]
        Jn_pos = [i for i in Jn if delta_j[i] > -eps]
        Jn_neg = [i for i in Jn if delta_j[i] <= -eps]
        
        if verbose:
            print('\nStep 9\n')
            print(f'A_b = {dataset["A"][:, dataset["Jb"]]}')
            print(f'B = {B}')
            print(f'Jn = {Jn}')
            print(f'Jn+ = {Jn_pos}')
            print(f'Jn- = {Jn_neg}')
        
    print(f'\nBest found solution: {x}')

**Задача а)**

In [19]:
solve(dataset)

A_b = [[ 1.  0. -1.  7.]
 [-1.  1.  1.  1.]
 [ 1.  1.  4.  2.]
 [ 1.  0.  3.  1.]]
c_b = [12. -6.  4. 23.]
B = [[ 0.         -1.          1.         -1.        ]
 [-0.09090909 -0.45454545  1.45454545 -1.81818182]
 [-0.04545455  0.27272727 -0.27272727  0.59090909]
 [ 0.13636364  0.18181818 -0.18181818  0.22727273]]
Jb = [0, 2, 5, 8]

Step 1

y = [ 3.5 -4.  -2.   6.5]
delta j = [ 1.77635684e-15 -5.00000000e+00  8.88178420e-16 -2.30000000e+01
  8.50000000e+00 -1.77635684e-15 -1.20000000e+01  1.00000000e+00
  1.06581410e-14]
Jn = [1, 3, 4, 6, 7]
Jn+ = [4, 7]
Jn- = [1, 3, 6]


Iteration 1

Step 2

x = [-18.5          0.         -43.31818182   7.          -3.
  20.34090909   4.          -1.           2.47727273]

Step 4

jk = 0

Step 5

mu_jk = 1
delta y = [ 0. -1.  1. -1.]
mu_j = [ 1.  0.  0.  5. -1.  0.  3. -1.  0.]

Step 6

sigma_j = [inf inf inf 4.6 8.5 inf 4.  1.  inf]
j* = 7
sigma0 = 1.0000000000000018

Step 8

New delta j = [  1.   -5.    0.  -18.    7.5   0.   -9.    0.    0. ]
Jb = 

**Задача б)**

In [20]:
solve(dataset_b, verbose=False)


Optimal plan: [-1.         -1.65714286 -1.          4.5        -3.          6.10714286
  4.          4.         -2.29285714]

cx = -104.5357142857143


**Задача в)**

In [21]:
solve(dataset_c, verbose=False)


Solution does not exist


**Задача г)**

In [22]:
solve(dataset_d, verbose=False)


Optimal plan: [-1.         -1.65714286 -1.          4.5        -3.          6.10714286
  4.          4.         -2.29285714]

cx = -104.53571428571429
